-- MySQL Script generated by MySQL Workbench
-- lun. 09 déc. 2019 16:41:45 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easy_nounou
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `easy_nounou` ;

-- -----------------------------------------------------
-- Schema easy_nounou
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easy_nounou` DEFAULT CHARACTER SET utf8 ;
USE `easy_nounou` ;

-- -----------------------------------------------------
-- Table `easy_nounou`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`admin` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`employer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`employer` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`employer` (
  `employer_id` INT NOT NULL AUTO_INCREMENT,
  `salary` VARCHAR(45) NULL,
  `regime_special` TINYINT(1) NULL,
  `caf_id` VARCHAR(45) NULL,
  `urssaf_id` VARCHAR(45) NULL,
  PRIMARY KEY (`employer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`employee` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` INT(45) NULL,
  `taux_horaire` FLOAT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`child` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`child` (
  `child_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `birthdate` VARCHAR(45) NULL,
  `contract_id` INT NULL,
  `employer_id` INT NULL,
  PRIMARY KEY (`child_id`),
  INDEX `fk_child_1_idx` (`employer_id` ASC),
  CONSTRAINT `fk_child_1`
    FOREIGN KEY (`employer_id`)
    REFERENCES `easy_nounou`.`employer` (`employer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`contract` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`contract` (
  `contract_id` INT NOT NULL AUTO_INCREMENT,
  `employer_id` INT NULL,
  `employee_id` INT NULL,
  `contract_url` VARCHAR(45) NULL,
  `share_id` INT NULL,
  PRIMARY KEY (`contract_id`),
  INDEX `fk_contract_1_idx` (`employer_id` ASC),
  INDEX `fk_contract_2_idx` (`employee_id` ASC),
  CONSTRAINT `fk_contract_1`
    FOREIGN KEY (`employer_id`)
    REFERENCES `easy_nounou`.`employer` (`employer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `easy_nounou`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`payslip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`payslip` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`payslip` (
  `payslip_id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` INT NULL,
  `employee_id` INT NULL,
  PRIMARY KEY (`payslip_id`),
  INDEX `fk_payslip_1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_payslip_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `easy_nounou`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`survey` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`survey` (
  `survey_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`survey_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`charge_patronale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`charge_patronale` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`charge_patronale` (
  `charge_patronale_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`charge_patronale_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`charge-salariale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`charge-salariale` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`charge-salariale` (
  `charge-salariale_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`charge-salariale_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`aides`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`aides` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`aides` (
  `aides_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`aides_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`user` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `employer_id` INT NULL,
  `employee_id` INT NULL,
  `admin_id` INT NULL,
  `phone_number` INT(45) NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_1_idx` (`employer_id` ASC),
  INDEX `fk_user_2_idx` (`admin_id` ASC),
  INDEX `fk_user_3_idx` (`employee_id` ASC),
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`employer_id`)
    REFERENCES `easy_nounou`.`employer` (`employer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_2`
    FOREIGN KEY (`admin_id`)
    REFERENCES `easy_nounou`.`admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_3`
    FOREIGN KEY (`employee_id`)
    REFERENCES `easy_nounou`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy_nounou`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_nounou`.`calendar` ;

CREATE TABLE IF NOT EXISTS `easy_nounou`.`calendar` (
  `calendar_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `minute_nb` INT NULL,
  `child_id` INT NULL,
  `relation_id` INT NULL,
  PRIMARY KEY (`calendar_id`),
  INDEX `fk_calendar_1_idx` (`child_id` ASC),
  CONSTRAINT `fk_calendar_1`
    FOREIGN KEY (`child_id`)
    REFERENCES `easy_nounou`.`child` (`child_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
